// Code generated by go-swagger; DO NOT EDIT.

/*Package restapi To Do List

To do list desc


    Schemes:
      http
      https
    Host: localhost
    BasePath: /
    Version: 0.1.0

    Consumes:
    - application/json


    Produces:
    - application/json


swagger:meta
*/
package restapi
